name: Code Integrity Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install --global prettier eslint
          npm ci || npm install

      - name: Lint and fix common issues
        run: |
          npx prettier --write .
          npx eslint . --ext .js,.jsx,.json,.yml --fix || true

      - name: Commit fixes if any
        run: |
          git config user.name "AutoFix Bot"
          git config user.email "bot@mycryptofi.ai"
          git add .
          git commit -m "Auto-fixed code formatting and syntax" || echo "No fixes needed"
          git push
