name: Update 3D Front (Local Zip)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # Ajaa joka päivä klo 05:00

jobs:
  update_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Extract mycryptofi-3d.zip
        run: |
          unzip -o mycryptofi-3d.zip -d ./_front

      - name: Replace site files
        run: |
          rm -rf src public index.html package.json tailwind.config.js postcss.config.js vite.config.js
          cp -r ./_front/* .
          rm -rf ./_front

      - name: Commit and push
        run: |
          git config user.name "MyCryptoFI Bot"
          git config user.email "bot@mycryptofi.com"
          git add .
          git commit -m "Auto-update Render style 3D front" || echo "No changes"
          git push
