name: Fetch crypto news

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # Ajetaan automaattisesti 4 tunnin välein

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser openai

      - name: Verify environment
        run: |
          echo "Tarkistetaan ympäristö..."
          python --version
          echo "OPENAI_API_KEY asetettu: ${{ secrets.OPENAI_API_KEY != '' }}"

      - name: Run bot.py to fetch and translate news
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "=== Suoritetaan uutisbotti ==="
          python bot.py || { echo "bot.py epäonnistui"; exit 1; }

      - name: Debug output (näytä viimeiset rivit latest.json:sta)
        run: |
          echo "=== Näytetään latest.json ==="
          tail -n 40 latest.json || echo "latest.json puuttuu"

      - name: Commit & Push updated news
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.json
          git commit -m "Päivitetyt kryptouutiset" || echo "Ei uusia muutoksia"
          git push
