name: Fetch crypto news
on:
  schedule:
    - cron: "0 * * * *"   # ajaa joka tunti
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate latest.json
        run: |
          python bot.py

      - name: Commit & push latest.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add latest.json
          git diff --cached --quiet && echo "No changes" || (git commit -m "chore: update latest.json" && git push)
